const root = document.getElementById('root');
const modalTitle = document.getElementById('mtitle');
const modalBody = document.getElementById('mbody');
const S = { page:'home', token:localStorage.getItem('valeris_token')||'', user:null, data:null, balanceVisible:true };

const TASKS = [
 ['dailyCheckIn','Daily Check-in','Confirm today’s check-in and start your earning day.',50,'✓'],
 ['financialKnowledgeQuiz','Financial Knowledge Quiz','Answer three short financial knowledge questions.',100,'?'],
 ['investmentArticle','Read an Investment Article','Read a short lesson and share one takeaway.',75,'▤'],
 ['cryptoMemoryPuzzle','Crypto Memory Puzzle','Complete a matching-memory challenge.',80,'◈'],
 ['bitcoinJigsawPuzzle','Bitcoin Jigsaw Puzzle','Solve the educational word puzzle.',90,'⌘'],
 ['investmentEducation','Investment Education','Complete a mini learning module.',120,'◫'],
 ['completeSurvey','Complete Survey','Share your feedback through a real survey form.',60,'☷'],
 ['marketWatch','Market Watch','Review a market scenario and make a choice.',70,'↗'],
 ['budgetPlanner','Budget Planner','Build a simple balanced monthly budget.',85,'£'],
 ['securityCheck','Security Check','Pass a short account-security checklist.',65,'♜'],
 ['fundYourWallet','Fund Your Wallet','Fund your demo wallet with £1,000 or more and complete the server verification step.',200,'▣']
];
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>'£'+Number(n||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
const logo = `<img class="brand-mark" src="assets/valerisbank-logo.svg" alt="ValerisBank logo"><span>ValerisBank<small>EARN AND GROW</small></span>`;

async function api(path,opt={}){
  const headers={'Content-Type':'application/json',...(opt.headers||{})};
  if(S.token) headers.Authorization='Bearer '+S.token;
  const response=await fetch(path,{...opt,headers});
  const data=await response.json().catch(()=>({message:'Server error'}));
  if(!response.ok) throw Error(data.message||'Request failed');
  return data;
}
function go(page){S.page=page;render();window.scrollTo({top:0,behavior:'smooth'})}
function modal(title,body){modalTitle.textContent=title;modalBody.innerHTML=body;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function toast(message){let el=document.getElementById('toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';document.body.append(el)}el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3800)}
async function session(){if(!S.token)return;try{S.user=(await api('/api/me')).user;S.data=(await api('/api/me/data')).data}catch{S.token='';localStorage.removeItem('valeris_token')}}
async function refresh(){S.data=(await api('/api/me/data')).data;render()}
function totalBalance(d=S.data||{}){return Number(d.mainBalance||0)+Number(d.taskBalance||0)+Number(d.investmentBalance||0)+Number(d.investmentProfit||0)}
function activeInvestments(){return (S.data?.investments||[]).filter(i=>i.status==='active')}

function publicHeader(){return `<header class="header"><div class="container"><div class="logo logo-flex" onclick="go('home')">${logo}</div><nav class="nav"><a onclick="go('personal')">Personal</a><a onclick="go('products')">Products</a><a onclick="go('about')">About Us</a><a onclick="go('tasks')">Tasks</a><a onclick="window.open('https://t.me/ValerisManagement','_blank')">Support</a></nav><div class="actions"><button class="btn outline" onclick="go('login')">Login</button><button class="btn primary" onclick="go('signup')">Open an Account</button></div></div></header>`}
function footer(){return `<footer class="footer"><div class="container"><div class="footgrid"><div><div class="logo logo-flex">${logo}</div><p style="color:var(--muted);font-size:13px">A polished interactive demo with separate member dashboards and saved test data.</p></div><div><h4>Features</h4><a onclick="go('personal')">Personal dashboard</a><a onclick="go('tasks')">Participative tasks</a><a onclick="go('investment')">Investment demo</a></div><div><h4>Company</h4><a onclick="go('about')">About ValerisBank</a><a onclick="go('products')">Products</a></div><div><h4>Support</h4><a onclick="window.open('https://t.me/ValerisManagement','_blank')">Telegram Support</a></div></div><div class="copyright">© 2026 ValerisBank demonstration interface. No real banking, investment or financial transactions are processed.</div></div></footer>`}
function shell(x){return publicHeader()+x+footer()}

function home(){return shell(`<main>
<section class="hero hero-pro"><div class="container hero-grid"><div class="reveal"><div class="kicker">Modern banking experience</div><h1>Grow Smarter.<br><span>Move Forward.</span></h1><p>Manage your personal demo dashboard, participate in interactive earning activities, track progress and explore investment simulations in one polished ValerisBank experience.</p><div class="hero-buttons"><button class="btn primary" onclick="go('signup')">Open an Account</button><button class="btn outline" onclick="go('login')">Login</button></div><div class="trust-row"><span>◉ Secure demo environment</span><span>◉ Individual dashboards</span><span>◉ 24/7 support</span></div></div><div class="hero-visual reveal delay"><img src="assets/banking-visual.png" alt="Modern digital banking workspace"><div class="floating-card"><span>Portfolio Growth</span><strong>+30% Demo Return</strong><small>After 24-hour simulation</small></div></div></div></section>
<section class="section section-soft"><div class="container"><div class="section-head"><div><div class="kicker">Everything connected</div><h2>One dashboard. More ways to participate.</h2><p>ValerisBank brings your account overview, wallet activity, participative tasks, investment simulations and withdrawal tracking together in one organized member experience.</p></div></div><div class="cards"><div class="card feature-card"><div class="icon">▣</div><h3>Fund Wallet</h3><p>Use the verification flow and see your saved demo balance update on your individual member dashboard.</p></div><div class="card feature-card"><div class="icon">☷</div><h3>Participative Tasks</h3><p>Complete quizzes, surveys, puzzles, lessons and other interactive activities before eligible demo rewards are recorded.</p></div><div class="card feature-card"><div class="icon">↗</div><h3>Investment Simulation</h3><p>Explore a clearly labelled 24-hour simulation and track simulated capital and profit through your portfolio.</p></div><div class="card feature-card"><div class="icon">◌</div><h3>Analytics & Activity</h3><p>Follow your balances, earnings, investments and recent activity from one easy-to-read dashboard.</p></div></div></div></section>
<section class="section"><div class="container"><div class="article-wrap"><div class="article-main"><div class="kicker">About ValerisBank</div><h2>A smarter, simpler way to experience digital finance.</h2><p>ValerisBank is designed around one simple idea: give every member a clear place to understand their account activity, explore financial learning opportunities and manage their personal dashboard with confidence. Instead of spreading information across different screens, the platform brings important account functions into one structured experience.</p><p>From the moment a member signs in, the dashboard provides a clear overview of balances, task earnings, investment activity and recent transactions. The experience is designed to be straightforward, so members can quickly understand where they stand, review what they have done and choose what to explore next.</p><p>ValerisBank also makes participation more engaging. Available tasks turn learning and simple activities into interactive experiences, while the investment area provides an illustrative simulation for users who want to understand how capital, simulated profit and maturity can be represented inside a digital dashboard.</p><p>Every member account is handled as an individual profile, with its own saved dashboard data, activity history, task progress and investment records. This makes the experience personal and organized rather than presenting every user with the same shared information.</p><p class="article-note"><strong>Important:</strong> ValerisBank is currently an interactive demonstration platform. Its funding, balances, withdrawals, tasks and investment features use test data; no real banking, investment or financial transactions are processed.</p></div><div class="article-side"><div class="card"><div class="icon">✓</div><h3>Built around clarity</h3><p>Simple navigation, clear status labels and organized account information help members understand each part of the experience.</p></div><div class="card"><div class="icon">↗</div><h3>Built for participation</h3><p>Interactive tasks and learning activities make the platform more engaging while keeping the experience easy to follow.</p></div><div class="card"><div class="icon">◉</div><h3>Built for your account</h3><p>Each registered member has an individual profile and saved activity rather than a shared dashboard.</p></div></div></div></div></section>
<section class="section section-soft"><div class="container"><div class="section-head"><div><div class="kicker">Why members may find it useful</div><h2>Practical benefits in one place.</h2></div></div><div class="benefit-grid"><div class="benefit-item"><strong>01</strong><div><h3>See your position clearly</h3><p>Review your total balance, task earnings, investment activity and recent transactions without jumping between unrelated pages.</p></div></div><div class="benefit-item"><strong>02</strong><div><h3>Stay organized</h3><p>Your individual activity, completed tasks and investment records are kept together so your progress is easier to follow.</p></div></div><div class="benefit-item"><strong>03</strong><div><h3>Learn by doing</h3><p>Participative tasks turn financial topics, surveys and simple challenges into hands-on activities rather than passive reading.</p></div></div><div class="benefit-item"><strong>04</strong><div><h3>Track every step</h3><p>Funding, investment simulations and withdrawals have visible statuses so you can follow what is happening in the interface.</p></div></div></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><div class="kicker">Member feedback</div><h2>What users appreciate about the experience.</h2><p>These are illustrative feedback examples for the demonstration website. Replace them with verified customer comments before publishing as real testimonials.</p></div></div><div class="testimonial-grid"><div class="testimonial card"><div class="stars">★★★★★</div><p>“The dashboard makes it easy to see my activity and understand where everything is without searching through different pages.”</p><strong>— Illustrative member comment</strong></div><div class="testimonial card"><div class="stars">★★★★★</div><p>“I like that the tasks are interactive. It feels more engaging than simply reading information and clicking a button.”</p><strong>— Illustrative member comment</strong></div><div class="testimonial card"><div class="stars">★★★★★</div><p>“The activity history and clear status updates make the whole account experience much easier to follow.”</p><strong>— Illustrative member comment</strong></div></div></div></section>
<section class="section cta"><div class="container"><div class="cta-box"><div class="kicker">Explore ValerisBank</div><h2>Experience a cleaner, smarter digital dashboard.</h2><p>Create your individual demo account and explore the features for yourself.</p><div class="hero-buttons" style="justify-content:center"><button class="btn primary" onclick="go('signup')">Open an Account</button><button class="btn outline" onclick="go('login')">Login</button></div></div></div></section>
</main>`)}

function auth(type){return `<main class="auth"><div class="auth-card reveal"><div class="logo logo-flex">${logo}</div><h1>${type==='login'?'Welcome back':'Open your account'}</h1><div class="notice">Demo only. No real money, banking or investment transactions are processed.</div><div id="authMsg"></div>${type==='signup'?`<div class="field"><label>First name</label><input id="firstName"></div><div class="field"><label>Last name</label><input id="lastName"></div><div class="field"><label>Country</label><input id="country"></div><div class="field"><label>Phone</label><input id="phone"></div>`:''}<div class="field"><label>${type==='login'?'Email or phone':'Email'}</label><input id="email"></div><div class="field"><label>Password</label><input id="pass" type="password"></div><button class="btn primary" onclick="${type==='login'?'login()':'signup()'}">${type==='login'?'Login':'Create Account'}</button><button class="btn outline back" onclick="go('home')">Back</button></div></main>`}
function msg(m){const e=document.getElementById('authMsg');if(e)e.innerHTML=`<div class="notice">${esc(m)}</div>`}
async function signup(){try{const r=await api('/api/signup',{method:'POST',body:JSON.stringify({firstName:firstName.value,lastName:lastName.value,country:country.value,phone:phone.value,email:email.value,password:pass.value})});S.token=r.token;localStorage.setItem('valeris_token',S.token);S.user=r.user;await refresh();S.page='dashboard';render()}catch(e){msg(e.message)}}
async function login(){try{const r=await api('/api/login',{method:'POST',body:JSON.stringify({identity:email.value,password:pass.value})});S.token=r.token;localStorage.setItem('valeris_token',S.token);S.user=r.user;await refresh();S.page='dashboard';render()}catch(e){msg(e.message)}}
async function logout(){try{await api('/api/logout',{method:'POST'})}catch{}S.token='';S.user=null;S.data=null;localStorage.removeItem('valeris_token');go('home')}

function appbar(){return `<div class="appbar"><div class="container"><div class="logo logo-flex" onclick="go('dashboard')">${logo}</div><div class="spacer"></div><div class="app-user"><span>Welcome, <b>${esc(S.user?.firstName||'Member')}</b></span><button class="profile-dot" onclick="go('profile')">${esc((S.user?.firstName||'M').slice(0,1))}</button><button class="btn app-logout" onclick="logout()">Logout</button></div></div></div>`}
function side(){return `<aside class="sidebar"><div class="side-brand">Member Area</div><button class="sidebtn ${S.page==='dashboard'?'active':''}" onclick="go('dashboard')">⌂ Overview</button><button class="sidebtn ${S.page==='fund'?'active':''}" onclick="go('fund')">▣ Fund Wallet</button><button class="sidebtn ${S.page==='tasks'?'active':''}" onclick="go('tasks')">☷ Tasks to Earn</button><button class="sidebtn ${S.page==='investment'?'active':''}" onclick="go('investment')">↗ Investment</button><button class="sidebtn ${S.page==='withdraw'?'active':''}" onclick="go('withdraw')">⇩ Withdraw</button><button class="sidebtn ${S.page==='transactions'?'active':''}" onclick="go('transactions')">≡ Transactions</button><h5>Account</h5><button class="sidebtn ${S.page==='profile'?'active':''}" onclick="go('profile')">◯ Profile</button><button class="sidebtn" onclick="window.open('https://t.me/ValerisManagement','_blank')">✈ Support</button><button class="sidebtn logout-side" onclick="logout()">↪ Logout</button></aside>`}
function appShell(x){return appbar()+`<style>.activity-withdrawal-row{cursor:pointer}.activity-withdrawal-row:hover{background:rgba(212,168,92,.08)}</style><div class="dashboard">${side()}<main class="dashmain"><div class="notice demo-notice">Simulation only: balances, funding, withdrawals, tasks and investments are saved test data for the individual logged-in member.</div>${x}</main></div><nav class="mobile-nav"><button onclick="go('dashboard')">⌂<span>Home</span></button><button onclick="go('fund')">▣<span>Fund</span></button><button onclick="go('withdraw')">⇩<span>Withdraw</span></button><button onclick="go('tasks')">☷<span>Tasks</span></button><button onclick="logout()">↪<span>Logout</span></button></nav>`}
function acts(){return (S.data?.activity||[]).slice().reverse()}

function earningsChart(){const d=S.data||{};const task=Number(d.taskEarnings||0), profit=Number(d.investmentProfit||0), wallet=Number(d.mainBalance||0);const values=[Math.max(0,wallet*.12),Math.max(0,wallet*.18+task*.1),Math.max(0,wallet*.24+task*.25),Math.max(0,wallet*.32+profit*.2),Math.max(0,wallet*.42+task*.35),Math.max(0,wallet*.55+profit*.45),Math.max(0,totalBalance())];const max=Math.max(...values,1);const points=values.map((v,i)=>`${20+i*48},${170-(v/max)*125}`).join(' ');const area=`20,170 ${points} 308,170`;return `<div class="panel chart-panel"><div class="chart-head"><div><h3>Earnings Overview</h3><p>Wallet, task rewards and investment performance</p></div><span class="chart-chip">This period</span></div><div class="line-chart"><svg viewBox="0 0 320 190" preserveAspectRatio="none"><defs><linearGradient id="investmentFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#14B8A6"/><stop offset="1" stop-color="#14B8A6" stop-opacity="0"/></linearGradient></defs><path d="M20 40H308 M20 82H308 M20 124H308 M20 170H308" class="chart-grid-line"/><polygon points="${area}" class="chart-area"/><polyline points="${points}" class="chart-line"/>${values.map((v,i)=>`<circle cx="${20+i*48}" cy="${170-(v/max)*125}" r="4" class="chart-dot"/>`).join('')}</svg></div><div class="chart-legend"><span>Task earnings: <strong>${fmt(task)}</strong></span><span>Investment profit: <strong>${fmt(profit)}</strong></span><span>Total: <strong>${fmt(totalBalance())}</strong></span></div></div>`}

function dashboard(){const d=S.data||{};const total=totalBalance(d);const active=activeInvestments().length;return appShell(`<div class="dash-title"><div><div class="kicker">ValerisBank member dashboard</div><h1>Welcome back, ${esc(S.user?.firstName||'Member')}</h1><p>Your activity, rewards and demo portfolio in one place.</p></div><button class="btn secondary" onclick="refresh()">↻ Refresh</button></div><div class="stats"><div class="stat stat-highlight"><div class="label">Total Balance</div><div class="balance-row"><strong>${S.balanceVisible?fmt(total):'••••••••'}</strong><button class="balance-toggle" onclick="S.balanceVisible=!S.balanceVisible;render()">◉</button></div><small>${active} active investment simulation${active===1?'':'s'}</small></div><div class="stat"><div class="label">Task Earnings</div><strong>${fmt(d.taskBalance)}</strong><div class="label">Participative rewards • withdrawable in demo</div></div><div class="stat"><div class="label">Investment Profit</div><strong>${fmt(d.investmentProfit)}</strong><div class="label">Settled after the demo maturity period</div></div></div><div class="quick quick-equal"><button class="btn secondary" onclick="go('fund')">＋ Fund Wallet</button><button class="btn secondary" onclick="go('withdraw')">⇩ Withdraw</button><button class="btn secondary" onclick="go('tasks')">☷ Tasks</button><button class="btn secondary" onclick="go('investment')">↗ Investment</button></div><div class="analytics-grid">${earningsChart()}<div class="panel summary-panel"><h3>Account Summary</h3><div class="summary-line"><span>Main wallet</span><strong>${fmt(d.mainBalance)}</strong></div><div class="summary-line"><span>Completed tasks</span><strong>${d.completedTasks||0}/10</strong></div><div class="summary-line"><span>Active investments</span><strong>${active}</strong></div><div class="summary-line"><span>Account</span><strong>${esc(S.user?.accountNumber||'')}</strong></div><button class="btn primary full-btn" onclick="go('tasks')">View Available Tasks</button></div></div><div class="panel activity-panel"><div class="chart-head"><div><h3>Recent Activity</h3><p>Saved to your individual member account</p></div><button class="text-btn" onclick="go('transactions')">View all</button></div><div class="tablewrap"><table class="table"><thead><tr><th>Description</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>${acts().slice(0,7).map(a=>`<tr class="${a.withdrawal?'activity-withdrawal-row':''}" ${a.withdrawal?`onclick="openWithdrawalActivity('${esc(a.id)}')" title="View withdrawal details"`:''}><td>${esc(a.title)}</td><td>${esc(a.date)}</td><td class="${a.amount<0?'amount-out':'amount-in'}">${a.amount<0?'-':'+'}${fmt(Math.abs(a.amount))}</td><td><span class="pill ${a.status==='Pending'?'pending':'ok'}">${esc(a.status)}</span></td></tr>`).join('')||'<tr><td colspan="4">No activity yet.</td></tr>'}</tbody></table></div></div>`)}

function transactions(){return appShell(`<div class="dash-title"><div><h1>Transactions</h1><p>Saved demo account activity for this member.</p></div></div><div class="panel"><div class="tablewrap"><table class="table"><thead><tr><th>Description</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>${acts().map(a=>`<tr><td>${esc(a.title)}<small class="desc">${esc(a.description||'')}</small></td><td>${esc(a.date)}</td><td>${fmt(a.amount)}</td><td><span class="pill ${a.status==='Active'||a.status==='Pending'?'pending':'ok'}">${esc(a.status)}</span></td></tr>`).join('')||'<tr><td colspan="4">No activity yet.</td></tr>'}</tbody></table></div></div>`)}

function fund(){return appShell(`<div class="dash-title"><div><h1>Fund Wallet</h1><p>Choose a funding method, enter your amount, then verify your test funding.</p></div></div><div class="card form-card"><div class="field"><label>Funding Method</label><select id="fundingMethod"><option value="bank-transfer">Bank Transfer</option><option value="card">Card</option><option value="wallet">Wallet</option><option value="crypto">Crypto</option></select></div><div class="field"><label>Funding Amount (£)</label><input id="fundAmount" type="number" min="1" placeholder="Enter amount"></div><div class="fund-code-row"><div class="field grow"><label>Funding Verification Code</label><input id="fundCode" inputmode="numeric" maxlength="6" placeholder="Enter 6-digit code"></div><button class="btn secondary code-btn" onclick="generateCode()">Generate Code</button></div><div class="notice">Demo code only: a new one-time code is generated for each request, expires after 5 minutes and is printed in your server/Render logs.</div><button class="btn primary full-btn" onclick="verifyFund()">Verify Funding</button></div>`)}
async function generateCode(){try{const r=await api('/api/test/verification-code',{method:'POST'});toast(r.message)}catch(e){toast(e.message)}}
async function verifyFund(){const amount=Number(document.getElementById('fundAmount')?.value);const code=document.getElementById('fundCode')?.value||'';if(!amount||amount<=0)return toast('Enter a valid funding amount.');if(!/^\d{6}$/.test(code))return toast('Enter the 6-digit verification code.');try{const r=await api('/api/test/fund',{method:'POST',body:JSON.stringify({amount,code})});toast(r.message);await refresh()}catch(e){toast(e.message)}}

function withdraw(){
 const d=S.data||{}; const eligible=Number(d.mainBalance||0)+Number(d.taskBalance||0)+Number(d.investmentProfit||0);
 const banks=['Barclays','HSBC UK','Lloyds Bank','NatWest','Santander UK','Halifax','Nationwide Building Society','Monzo','Revolut','JPMorgan Chase','Bank of America','Citibank','Wells Fargo','U.S. Bank','Capital One','Royal Bank of Canada (RBC)','TD Canada Trust','Scotiabank','Deutsche Bank','BNP Paribas','Société Générale','ING Bank','UniCredit','Banco Santander','BBVA','DBS Bank','OCBC Bank','United Overseas Bank (UOB)','Mizuho Bank','MUFG Bank','Bank of China','Industrial and Commercial Bank of China (ICBC)','Shinhan Bank','KB Kookmin Bank','Commonwealth Bank','ANZ','Westpac','National Australia Bank (NAB)'];
 return appShell(`<style>
 .withdraw-flow{max-width:820px;margin:auto}.withdraw-summary{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:20px}.withdraw-flow .form-card{padding:24px}.withdraw-flow .field{margin:14px 0}.withdraw-flow input{width:100%}.processing-page,.withdraw-status-page{max-width:720px;margin:10px auto;text-align:center}.processing-ring{width:145px;height:145px;border:10px solid #e5e8ee;border-top-color:var(--teal);border-radius:50%;margin:30px auto;display:grid;place-items:center;animation:spin 1.15s linear infinite}.processing-ring span{width:90px;height:90px;border-radius:50%;background:#fff;display:grid;place-items:center;font-size:25px;font-weight:800;color:var(--green);animation:counterspin 1.15s linear infinite}.withdraw-notice{background:var(--teal);color:var(--green);padding:22px;border-radius:18px;margin:28px 0;line-height:1.6}.progress-track2{height:11px;background:#e3e7ed;border-radius:20px;overflow:hidden}.progress-fill2{height:100%;background:var(--green);width:0%;transition:width .5s}.status-card{text-align:left;padding:28px;background:#fff;border:1px solid var(--line);border-radius:16px;box-shadow:0 8px 28px rgba(6,59,50,.06)}.detail-row2{display:grid;grid-template-columns:minmax(150px,32%) 1fr;align-items:start;column-gap:32px;padding:16px 0;border-bottom:1px solid var(--line);line-height:1.5}.detail-row2 span{color:var(--muted);font-weight:600}.detail-row2 strong{color:var(--ink);font-weight:800;text-align:left;overflow-wrap:anywhere}.timeline2{margin:28px 0;text-align:left}.timeline-item2{display:flex;gap:14px;margin:18px 0}.marker2{width:28px;height:28px;border-radius:50%;background:var(--teal);color:var(--green);display:grid;place-items:center;font-weight:800;flex:0 0 28px}.bottom-processing2{display:flex;gap:14px;align-items:center;background:#EEF8F6;border:1px solid #CFEAE5;padding:18px;border-radius:14px;text-align:left}@keyframes spin{to{transform:rotate(360deg)}}@keyframes counterspin{to{transform:rotate(-360deg)}}@media(max-width:650px){.withdraw-summary{grid-template-columns:1fr}.detail-row2{grid-template-columns:1fr;row-gap:6px;padding:15px 0}.detail-row2 strong{text-align:left}.withdraw-flow{width:100%}.withdraw-flow .form-card{padding:18px}.processing-page,.withdraw-status-page{width:100%;padding:0 2px}}
 </style><div class="withdraw-flow"><div class="dash-title"><div><div class="kicker">Demo withdrawal interface</div><h1>Withdraw</h1><p>Submit a withdrawal request using the full processing flow.</p></div></div><div class="withdraw-summary"><div class="card"><h3>Available to Withdraw</h3><div class="big-number">${fmt(eligible)}</div><p>Main wallet, task rewards and settled demo investment profit are included.</p></div><div class="card"><h3>Processing Status</h3><p>Requests move through a visual processing sequence for interface testing.</p></div></div><div class="card form-card"><form id="withdrawForm" onsubmit="event.preventDefault();submitWithdraw()"><div class="field"><label>Withdrawal Amount (£)</label><input id="withdrawAmount" type="number" min="1" step="0.01" max="${eligible}" placeholder="Enter amount" required></div><div class="field"><label>Bank</label><input id="withdrawBank" list="withdrawBankList" placeholder="Search or select a bank" required><datalist id="withdrawBankList">${banks.map(b=>`<option value="${b}"></option>`).join('')}</datalist></div><div class="field"><label>Recipient Name</label><input id="withdrawRecipient" type="text" placeholder="Enter recipient name" required></div><div class="field"><label>Account Number / IBAN</label><input id="withdrawIban" type="text" placeholder="Enter account number or IBAN" required></div><div class="field"><label>Mobile Number</label><input id="withdrawMobile" type="tel" placeholder="Enter mobile number" required></div><div class="field"><label>Email Address</label><input id="withdrawEmail" type="email" placeholder="Enter email address" required></div><button class="btn primary full-btn" type="submit">Continue to Processing</button></form></div></div>`)}

function submitWithdraw(){
 const form=document.getElementById('withdrawForm'); if(!form) return; const data={amount:Number(document.getElementById('withdrawAmount').value),bank:document.getElementById('withdrawBank').value.trim(),recipientName:document.getElementById('withdrawRecipient').value.trim(),iban:document.getElementById('withdrawIban').value.trim(),mobile:document.getElementById('withdrawMobile').value.trim(),email:document.getElementById('withdrawEmail').value.trim()};
 if(!data.amount||data.amount<=0||!data.bank||!data.recipientName||!data.iban||!data.mobile||!data.email) return toast('Please complete all withdrawal details.'); showWithdrawalProcessing(data);
}

function showWithdrawalProcessing(data){
 // Demo-only visual processing flow. Progress advances every 3 seconds.
 const values=[10,20,30,40,50,60,65,70,80,90,100];
 root.innerHTML=appShell(`<div class="processing-page"><div class="processing-ring"><span id="wpct">0%</span></div><h1>Processing your transaction</h1><p class="muted">Almost ready, please wait while your request is being prepared.</p><div class="withdraw-notice" id="wnotice">Your withdrawal request is being securely prepared for processing.</div><div class="card" style="padding:22px;text-align:left;margin-top:25px"><div style="display:flex;justify-content:space-between;margin-bottom:10px"><strong>Processing</strong><strong id="wprog">0%</strong></div><div class="progress-track2"><div class="progress-fill2" id="wfill"></div></div></div><div class="status" style="margin-top:25px">● <span id="wstatus">Processing your transaction...</span></div></div>`);
 let i=0;
 const timer=setInterval(()=>{
   const v=values[i++];
   const p=document.getElementById('wpct'),pr=document.getElementById('wprog'),f=document.getElementById('wfill');
   if(p)p.textContent=v+'%';
   if(pr)pr.textContent=v+'%';
   if(f)f.style.width=v+'%';
   if(v===65){
     const n=document.getElementById('wnotice');
     if(n)n.textContent='Your withdrawal has been processed.';
     const st=document.getElementById('wstatus');
     if(st)st.textContent='Your withdrawal has been processed.';
   }
   if(v===100){
     clearInterval(timer);
     setTimeout(()=>finalizeWithdrawal(data),900);
   }
 },3000);
}

async function finalizeWithdrawal(data){try{const r=await api('/api/test/withdraw',{method:'POST',body:JSON.stringify({amount:data.amount,bank:data.bank,recipientName:data.recipientName,iban:data.iban,mobile:data.mobile,email:data.email})}); showWithdrawalStatus(data,r.message||'Your withdrawal request is pending processing.')}catch(e){toast(e.message);S.page='withdraw';render()}}

function openWithdrawalActivity(id){
 const item=(S.data?.activity||[]).find(a=>a.id===id);
 if(!item?.withdrawal) return toast('Withdrawal details are not available for this activity.');
 showWithdrawalStatus(item.withdrawal,'Your withdrawal request is pending processing.');
}

function showWithdrawalStatus(data,message){
 root.innerHTML=appShell(`<div class="withdraw-final-page">
   <div class="withdraw-final-head">
     <div class="withdraw-final-brand">${logo}</div>
     <button class="withdraw-final-close" onclick="refresh()" aria-label="Close">×</button>
     <div class="withdraw-final-progress"><span class="active"></span><i></i><span class="active"></span><i></i><span class="active"></span><i></i><span></span></div>
   </div>
   <div class="withdraw-final-content">
     <h1>Your withdrawal has started processing!</h1>
     <p class="withdraw-final-subtitle">Your withdrawal request has been received. We are processing your funds for disbursement.</p>
     <div class="card withdraw-final-card">
       <div class="detail-row2"><span>Amount</span><strong>${fmt(data.amount)}</strong></div>
       <div class="detail-row2"><span>Bank</span><strong>${esc(data.bank)}</strong></div>
       <div class="detail-row2"><span>Recipient Name</span><strong>${esc(data.recipientName)}</strong></div>
       <div class="detail-row2"><span>Account Number</span><strong>${esc(data.iban)}</strong></div>
       <div class="detail-row2"><span>Mobile</span><strong>${esc(data.mobile)}</strong></div>
       <div class="detail-row2"><span>Email</span><strong>${esc(data.email)}</strong></div>
       <div class="detail-row2 final-status-row"><span>Status</span><strong>Processing</strong></div>
       <div class="timeline2">
         <div class="timeline-line"></div>
         <div class="timeline-item2 current"><div class="marker2 current-marker">●</div><div><h3>Processing</h3><p>ValerisBank is processing your withdrawal request.</p></div></div>
         <div class="timeline-item2"><div class="marker2">✓</div><div><small>Withdrawal approved</small><h3>Approved</h3><p>Your withdrawal request has been approved for processing.</p></div></div>
         <div class="timeline-item2"><div class="marker2">✓</div><div><small>Withdrawal received</small><h3>Withdrawal Requested</h3><p>Your online banking withdrawal request has been received.</p></div></div>
       </div>
       <div class="bottom-processing2"><div class="marker2 current-marker">●</div><div><strong>Processing</strong><p>Your withdrawal is currently being processed.</p></div></div>
     </div>
   </div>
 </div>`)
}
function taskDoneToday(done,id){
 const value=done?.[id];
 if(!value)return false;
 return String(value).slice(0,10)===new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos'}).format(new Date());
}
function tasks(){
 const done=S.data?.dailyTaskCompletions||{};
 const completed=TASKS.filter(t=>taskDoneToday(done,t[0])).length;
 return appShell(`<div class="dash-title"><div><div class="kicker">Participate to earn</div><h1>Tasks to Earn</h1><p>Tasks reset by calendar day and become available again at 00:00. Rewards are added only after valid completion.</p></div><div class="task-progress"><strong>${completed}/${TASKS.length}</strong><span>Completed today</span></div></div><div class="task-list">${TASKS.map(t=>{const doneToday=taskDoneToday(done,t[0]);return `<div class="task-row ${doneToday?'task-done':''}"><div class="task-icon">${t[4]}</div><div class="task-content"><h3>${t[1]}</h3><p>${t[2]}</p></div><div class="task-reward">${fmt(t[3])}</div><button class="btn secondary" ${doneToday?'disabled':''} onclick="openTask('${t[0]}')">${doneToday?'Completed':'Start Task'}</button></div>`}).join('')}</div>`)}

function openTask(id){const task=TASKS.find(t=>t[0]===id);if(!task)return;const title=task[1];let body='';
if(id==='dailyCheckIn') body=`<div class="task-modal"><p>Confirm that you are checking in today to receive the daily demo reward.</p><label class="checkline"><input id="tConfirm" type="checkbox"> I confirm my daily check-in.</label><button class="btn primary full-btn" onclick="submitTask('dailyCheckIn',{confirm:document.getElementById('tConfirm').checked})">Complete Check-in</button></div>`;
if(id==='financialKnowledgeQuiz') body=`<div class="task-modal"><p>Answer all three questions correctly.</p><div class="field"><label>1. A plan for tracking income and expenses is a:</label><select id="q1"><option value="">Choose</option><option value="budget">Budget</option><option value="loan">Loan</option></select></div><div class="field"><label>2. Spreading investments can support:</label><select id="q2"><option value="">Choose</option><option value="diversification">Diversification</option><option value="inflation">Inflation</option></select></div><div class="field"><label>3. The possibility of losing value is called:</label><select id="q3"><option value="">Choose</option><option value="risk">Risk</option><option value="profit">Profit</option></select></div><button class="btn primary full-btn" onclick="submitTask('financialKnowledgeQuiz',{q1:document.getElementById('q1').value,q2:document.getElementById('q2').value,q3:document.getElementById('q3').value})">Submit Quiz</button></div>`;
if(id==='investmentArticle') body=`<div class="task-modal"><article class="lesson"><h4>Why diversification matters</h4><p>Diversification means spreading exposure instead of relying on a single asset or category. In this demo lesson, the goal is simply to understand that concentration can increase the impact of one outcome.</p></article><label class="checkline"><input id="readArticle" type="checkbox"> I have read the lesson.</label><div class="field"><label>Write one takeaway (10+ characters)</label><textarea id="takeaway" placeholder="What did you learn?"></textarea></div><button class="btn primary full-btn" onclick="submitTask('investmentArticle',{read:document.getElementById('readArticle').checked,takeaway:document.getElementById('takeaway').value})">Submit Takeaway</button></div>`;
if(id==='cryptoMemoryPuzzle') body=`<div class="task-modal"><p>Select all four matching concept cards to complete the memory activity.</p><div class="memory-grid">${['Wallet','Block','Ledger','Key'].map(x=>`<button class="memory-card" onclick="toggleMemory(this,'${x}')">${x}</button>`).join('')}</div><p id="memoryStatus" class="label">0/4 selected</p><button class="btn primary full-btn" onclick="submitMemory()">Submit Puzzle</button></div>`;
if(id==='bitcoinJigsawPuzzle') body=`<div class="task-modal"><p>Unscramble this word: <strong>KCLOHBCIAN</strong></p><div class="field"><label>Your answer</label><input id="jigsawAnswer" placeholder="Enter the word"></div><button class="btn primary full-btn" onclick="submitTask('bitcoinJigsawPuzzle',{answer:document.getElementById('jigsawAnswer').value})">Check Answer</button></div>`;
if(id==='investmentEducation') body=`<div class="task-modal"><h4>Mini lesson: compounding</h4><p>Compounding describes growth being calculated on an amount that may already include previous growth. This activity is educational and does not promise any real-world return.</p><div class="field"><label>Choose the lesson keyword</label><select id="lesson"><option value="">Choose</option><option value="compound">Compound</option><option value="withdraw">Withdraw</option></select></div><label class="checkline"><input id="lessonConfirm" type="checkbox"> I completed the lesson.</label><button class="btn primary full-btn" onclick="submitTask('investmentEducation',{lesson:document.getElementById('lesson').value,confirm:document.getElementById('lessonConfirm').checked})">Complete Lesson</button></div>`;
if(id==='completeSurvey') body=`<div class="task-modal"><p>Please complete this short ValerisBank demo survey.</p><div class="field"><label>How would you rate this demo?</label><select id="surveyRating"><option value="">Choose</option><option value="excellent">Excellent</option><option value="good">Good</option><option value="average">Average</option><option value="poor">Poor</option></select></div><div class="field"><label>What would you improve?</label><textarea id="surveyFeedback" placeholder="At least 8 characters"></textarea></div><button class="btn primary full-btn" onclick="submitTask('completeSurvey',{rating:document.getElementById('surveyRating').value,feedback:document.getElementById('surveyFeedback').value})">Submit Survey</button></div>`;
if(id==='marketWatch') body=`<div class="task-modal"><p>Demo market scenario: a chart moves from 100 to 108. Which direction did it move?</p><div class="choice-row"><button class="choice" onclick="pickChoice('up',this)">Up</button><button class="choice" onclick="pickChoice('down',this)">Down</button><button class="choice" onclick="pickChoice('flat',this)">Flat</button></div><button class="btn primary full-btn" onclick="submitTask('marketWatch',{direction:window.marketChoice||''})">Submit Observation</button></div>`;
if(id==='budgetPlanner') body=`<div class="task-modal"><p>Create a simple budget where planned needs and savings do not exceed income.</p><div class="field"><label>Monthly income</label><input id="budgetIncome" type="number" min="1"></div><div class="field"><label>Planned needs</label><input id="budgetNeeds" type="number" min="0"></div><div class="field"><label>Planned savings</label><input id="budgetSavings" type="number" min="0"></div><button class="btn primary full-btn" onclick="submitTask('budgetPlanner',{income:document.getElementById('budgetIncome').value,needs:document.getElementById('budgetNeeds').value,savings:document.getElementById('budgetSavings').value})">Validate Budget</button></div>`;
if(id==='securityCheck') body=`<div class="task-modal"><p>Tick all three good security practices.</p><label class="checkline"><input id="sec1" type="checkbox"> Use a strong, unique password.</label><label class="checkline"><input id="sec2" type="checkbox"> Check unexpected links for phishing.</label><label class="checkline"><input id="sec3" type="checkbox"> Use two-factor authentication where available.</label><button class="btn primary full-btn" onclick="submitTask('securityCheck',{password:document.getElementById('sec1').checked,phishing:document.getElementById('sec2').checked,twoFactor:document.getElementById('sec3').checked})">Complete Security Check</button></div>`;
if(id==='fundYourWallet') body=`<div class="task-modal funding-task-modal"><div class="notice"><strong>Fund Your Wallet</strong><br>Fund at least £1,000 in the demo wallet to qualify for the £200 demo task reward.</div><div class="field"><label>Funding amount (£)</label><input id="fundTaskAmount" type="number" min="1000" step="0.01" placeholder="Minimum £1,000"></div><div class="fund-code-row"><div class="field"><label>6-digit verification code</label><input id="fundTaskCode" inputmode="numeric" maxlength="6" autocomplete="one-time-code" placeholder="000000"></div><button class="btn secondary code-btn" onclick="generateFundTaskCode()">Request Code</button></div><div class="notice">Demo verification: the six-digit code is generated on the server and printed in your server/Render logs. It expires after 5 minutes.</div><button class="btn primary full-btn" onclick="completeFundTask()">Verify & Complete Task</button></div>`;
modal(title,body)}
async function generateFundTaskCode(){
 try{
  const r=await api('/api/test/verification-code',{method:'POST'});
  toast(r.message);
 }catch(e){toast(e.message)}
}
async function completeFundTask(){
 const amount=Number(document.getElementById('fundTaskAmount')?.value);
 const code=document.getElementById('fundTaskCode')?.value?.trim()||'';
 if(!amount||amount<1000)return toast('Enter at least £1,000.');
 if(!/^\d{6}$/.test(code))return toast('Enter the 6-digit verification code.');
 try{
  const r=await api('/api/test/fund-task',{method:'POST',body:JSON.stringify({amount,code})});
  closeModal(); toast(r.message); await refresh(); render();
 }catch(e){toast(e.message)}
}
async function submitTask(id,payload){try{const r=await api('/api/test/tasks/'+id+'/submit',{method:'POST',body:JSON.stringify(payload)});closeModal();toast(r.message);await refresh()}catch(e){toast(e.message)}}
window.memoryChoices=[];
function toggleMemory(el,value){const list=window.memoryChoices||[];const i=list.indexOf(value);if(i>=0){list.splice(i,1);el.classList.remove('selected')}else if(list.length<4){list.push(value);el.classList.add('selected')}window.memoryChoices=list;const s=document.getElementById('memoryStatus');if(s)s.textContent=`${list.length}/4 selected`}
function submitMemory(){submitTask('cryptoMemoryPuzzle',{pairs:window.memoryChoices||[]})}
function pickChoice(value,el){window.marketChoice=value;document.querySelectorAll('.choice').forEach(b=>b.classList.remove('selected'));el.classList.add('selected')}

function investment(){const d=S.data||{};const active=activeInvestments();const activeHtml=active.map(i=>{const remaining=Math.max(0,new Date(i.maturesAt).getTime()-Date.now());const hours=Math.floor(remaining/3600000);const mins=Math.floor((remaining%3600000)/60000);return `<div class="investment-active"><div><span class="pill pending">Processing</span><h3>${fmt(i.amount)} demo investment</h3><p>Expected demo profit: <strong>${fmt(i.profit)}</strong></p></div><div class="countdown">${hours}h ${mins}m<small>until maturity</small></div></div>`}).join('');return appShell(`<div class="dash-title"><div><div class="kicker">24-hour simulation</div><h1>Investment</h1><p>Clearly labelled illustrative simulation only. No real investment product or return is being offered.</p></div></div><div class="investment-layout"><div class="card investment-single"><div class="investment-badge">Demo plan</div><h2>Valeris 24-Hour Growth Simulation</h2><div class="investment-rate">30%</div><p class="muted">Illustrative simulated profit after 24 hours. The simulation can use funds available across your total available balance (main wallet, task rewards and settled demo investment profit). At maturity, the demo returns the simulated capital plus the calculated demo profit to the member’s demo wallet.</p><div class="investment-meta"><div><span>Duration</span><strong>24 Hours</strong></div><div><span>Demo Return</span><strong>30%</strong></div><div><span>Source</span><strong>Total Available Balance</strong></div></div><div class="field"><label>Simulation Amount (£)</label><input id="investmentAmount" type="number" min="1" placeholder="Enter amount"></div><button class="btn primary full-btn" onclick="startInvestment()">Start 24-Hour Simulation</button></div><div class="investment-side"><div class="card"><h3>Active Simulations</h3>${activeHtml||'<p class="muted">No active investment simulations.</p>'}</div><div class="card"><h3>Portfolio Snapshot</h3><div class="summary-line"><span>Active capital</span><strong>${fmt(d.investmentBalance)}</strong></div><div class="summary-line"><span>Settled profit</span><strong>${fmt(d.investmentProfit)}</strong></div></div></div></div>`)}
async function startInvestment(){const amount=Number(document.getElementById('investmentAmount')?.value);if(!amount||amount<=0)return toast('Enter a valid amount.');try{const r=await api('/api/test/invest',{method:'POST',body:JSON.stringify({amount})});toast(r.message);await refresh()}catch(e){toast(e.message)}}

function profile(){return appShell(`<div class="dash-title"><div><h1>Profile</h1><p>Your saved member details.</p></div></div><div class="cards profile-grid"><div class="card"><h3>Personal Information</h3><p>Name<br><strong>${esc(S.user?.firstName)} ${esc(S.user?.lastName)}</strong></p><p>Email<br><strong>${esc(S.user?.email)}</strong></p><p>Phone<br><strong>${esc(S.user?.phone)}</strong></p></div><div class="card"><h3>Account</h3><p>Account Number<br><strong>${esc(S.user?.accountNumber)}</strong></p><p>Country<br><strong>${esc(S.user?.country)}</strong></p></div><div class="card"><h3>Support</h3><p>Contact ValerisBank support directly on Telegram.</p><button class="btn primary" onclick="window.open('https://t.me/ValerisManagement','_blank')">Open Telegram Support</button></div></div>`)}
function infoPage(t,l){return shell(`<main class="section"><div class="container"><div class="kicker">ValerisBank</div><h1 style="font-size:44px">${esc(t)}</h1><p style="color:var(--muted);max-width:720px;line-height:1.7">${esc(l)}</p></div></main>`)}
function render(){let r;if(S.page==='home')r=home();else if(S.page==='login'||S.page==='signup')r=auth(S.page);else if(!S.user){S.page='login';r=auth('login')}else if(S.page==='dashboard')r=dashboard();else if(S.page==='transactions')r=transactions();else if(S.page==='fund')r=fund();else if(S.page==='withdraw')r=withdraw();else if(S.page==='tasks')r=tasks();else if(S.page==='investment')r=investment();else if(S.page==='profile')r=profile();else r=infoPage(S.page,'ValerisBank information page.');root.innerHTML=r}
(async()=>{await session();if(S.user)S.page='dashboard';render()})();
